name = "AMGCLWrap"
uuid = "4f76b812-4ba5-496d-b042-d70715554288"
authors = ["Jürgen Fuhrmann <juergen-fuhrmann@web.de> and contributors"]
version = "0.3.1"

[deps]
AMGCL_C_jll = "e3ba5bb7-5aef-5326-9a13-9617383dcacb"
CompositeStructs = "534720e6-2374-40c5-8712-bf9a2f1643c6"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"

[compat]
AMGCL_C_jll = "0.3.0"
CompositeStructs = "0.1.5"
DocStringExtensions = "0.9"
JSON3 = "1.14.0"
LinearAlgebra = "1.6"
LinearSolve = "2.22"
SparseArrays = "1.6"
SparseMatricesCSR = "0.6.7"
julia = "1.6"

[extensions]
AMGCLWrapLinearSolveExt = "LinearSolve"

[extras]
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"

[weakdeps]
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
